- app/controllers/home_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/home/index.html.haml
- app/views/home/instructions.html.haml
- app/views/layouts/application.html.haml
- app/views/users/edit.html.haml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20160622064049_create_users.rb
- db/schema.rb
> less copy, instruction page, party affiliation

- app/controllers/concerns/ride_params.rb
- app/views/admin/rides/_form.html.haml
- app/views/admin/rides/show.html.haml
- db/migrate/20160812064433_add_special_requests_to_rides.rb
- db/schema.rb
I didn't add it to the Rides index page because the page is getting pretty crowded, column-wise
> Add special_requests to Ride

- .gitignore
Should prevent someone from accidentally commit precompiled assets
> add /public/assets to gitignore

- app/controllers/api/v1/twilio_controller.rb
- app/models/conversation.rb
- app/models/user.rb
- db/migrate/20160812023206_change_user_phone_index.rb
- db/schema.rb
- spec/controllers/api/v1/twilio_controller_spec.rb
So testers can sign up different ways. This replaces the older PR which had rebase issues due to things moving around.
> Change the user to allow for multiple users with same phone number

- public/map/icon-default.svg
- public/map/index.html
Followup to https://github.com/DevProgress/drive.vote/pull/48.
New code sample:
```Javascript
new Map(document.getElementById('map'),
function(map)
{
// Add a bunch of markers
var m1 = map.addMarker(37.770444, -122.434960, Map.icons.voter, 'Hello World!', 'http://example.com');
var m2 = map.addMarker(37.769079, -122.433674, Map.icons.poll,  'Hello World!');
var m3 = map.addMarker(37.771612, -122.426836, Map.icons.driver);
// Update each of the markers
map.updateMarker(m1, 37.770709, -122.435082, Map.icons.driver, 'Goodbye World!', 'http://example.com');
map.updateMarker(m2, 37.768962, -122.433387, Map.icons.voter,  'Goodbye World!');
map.updateMarker(m3, 37.771455, -122.428098, Map.icons.poll);
},
{lat: 37.77073, lon: -122.43020, zoom: 16});
```
> Added ability to update map marker pin locations and popups

- app/controllers/admin/rides_controller.rb
- app/controllers/api/v1/ride_zones_controller.rb
- app/models/conversation.rb
- app/models/ride.rb
- doc/dispatch_api.yaml
- spec/models/conversation_spec.rb
Do we want admin UI to support attaching ride to conversation?
> Create the ride-conversation association and conversation status update

- app/controllers/admin/users_controller.rb
- app/controllers/concerns/user_roles.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/admin/users/_form.html.haml
- app/views/admin/users/show.html.haml
- spec/models/user_spec.rb
John already added some of my changes in an earlier PR, but this fixes a few things.
> Clean up Admin Users CRUD a bit

- .eslintrc.js
- README.md
- app/javascript/driving/actions/actionCreators.js
- app/javascript/driving/components/ActiveRide.js
- app/javascript/driving/components/AppError.js
- app/javascript/driving/components/AvailableButton.js
- app/javascript/driving/components/ContactVoter.js
- app/javascript/driving/components/DispatchMatch.js
- app/javascript/driving/components/Header.js
- app/javascript/driving/components/Loading.js
- app/javascript/driving/components/PendingRide.js
- app/javascript/driving/components/PendingRideDetail.js
- app/javascript/driving/components/Unavailable.js
- app/javascript/driving/components/UnavailableButton.js
- app/javascript/driving/containers/App.js
- app/javascript/driving/containers/DriverStatusContainer.js
- app/javascript/driving/containers/LocationManager.js
- app/javascript/driving/containers/Main.js
- app/javascript/driving/containers/RideContainer.js
- app/javascript/driving/containers/WaitingRidesContainer.js
- app/javascript/driving/helpers/helpers.js
- app/javascript/driving/index.js
- app/javascript/driving/reducers/rootReducer.js
- app/javascript/driving/store.js
- app/javascript/driving/styles/drive-vote.css
- config/eslint.js
- package.json
- yarn.lock
This PR updates our ESLint config, runs Prettier against driver app files and fixes issues causing lint errors.
ESLint config changes:
- Switches our ESLint config to a dotfile (`.eslintrc`), which can be automatically loaded by IDEs.
- Switch from a custom ruleset to configurations actively maintained by teams of very smart people: [Airbnb](https://github.com/airbnb/javascript) & [ESLint-plugin-React](https://github.com/yannickcr/eslint-plugin-react)
Almost all of the code changes are style/syntax related and can be attributed to:
* [Prettier](https://github.com/prettier/prettier) fixing my ugly, manually formatted code.
* [Destructuring assignments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring) for props …
> Update ESLint config, fix errors and run Prettier

- Dockerfile
- README.md
- docker-compose.yml
- Added postgresql-client to the Dockerfile
- In docker-compose switched to postgres:10.5-alpine and redis:4.0.11-alpine, rather than just 'postgres' and 'redis'
> Docker image tags, Dockerfile update

- app/controllers/admin/drivers_controller.rb
- app/controllers/admin/users_controller.rb
- app/models/user.rb
- app/views/admin/drivers/index.html.haml
- app/views/admin/users/voters.html.haml
> Admin app updates

- app/javascript/driving/components/ActiveRide.js
- app/javascript/driving/components/AppError.js
- app/javascript/driving/components/AvailableButton.js
- app/javascript/driving/components/ContactVoter.js
- app/javascript/driving/components/Header.js
- app/javascript/driving/components/PendingRide.js
- app/javascript/driving/components/PendingRideDetail.js
- app/javascript/driving/components/Unavailable.js
- app/javascript/driving/components/UnavailableButton.js
- app/javascript/driving/containers/App.js
- app/javascript/driving/containers/DriverStatusContainer.js
- app/javascript/driving/containers/LocationManager.js
- app/javascript/driving/containers/RideContainer.js
- app/javascript/driving/containers/WaitingRidesContainer.js
- app/javascript/driving/helpers/helpers.js
- app/javascript/driving/reducers/rootReducer.js
- package.json
* Adds PropType checking for all components, lint now passes for the driver app 🎉 
* Refactors redux state shape, which was unnecessarily stored under `state.driverState`
@jamesarosen @galencorey
> Add PropType checking, refactor redux state shape.

- app/javascript/driving/actions/actionCreators.js
- app/javascript/driving/components/ActiveRide.js
- app/javascript/driving/reducers/rootReducer.js
- app/javascript/driving/styles/drive-vote.scss
Adds archive button for rides in-progress, implementing #838 
I think we're going to want revisit the copy/UX of the ride flow in the driver app, there's a lot of buttons to press now 😅 
cc @jamesarosen @john @galencorey
> Add archive button

- app/javascript/driving/components/ActiveRide.js
> Add zip to ActiveRide

- app/controllers/rides_controller.rb
If the @user variable is set, the new ride form doesn't render the name/phone/email fields
> Issue #939 Reset user variable for proper rerendering of new ride form

- app/controllers/application_controller.rb
- app/controllers/concerns/user_params.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.haml
- config/locales/en.yml
- config/locales/es.yml
- config/routes.rb
- db/migrate/20180903172250_add_driver_info_to_user.rb
- db/schema.rb
@john i uncommented the volunteer routes to test - do we want them to exist or not? Not sure how we created drivers w/o them.
Should we be sending the license plate to the voter as part of "driver on the way" message? In this issue or different one?
> Issue #934 collect drivers license and license plate from volunteer form

- app/assets/javascripts/dispatch_map.js.erb
Make the maps grayscale so it's easier to see voters & drivers.
Closes #921
> Add 'silver' styles from mapstyle.withgoogle.com

- app/assets/stylesheets/drive.vote.css.scss
- app/views/admin/conversations/_table.html.haml
- app/views/dispatch/_messages.html.haml
- app/views/dispatch/_modal.html.haml
Change copy and styles to clarify 'cancel ride' button in dispatcher modal. Closes #883
> Cancel ride style & copy

- app/controllers/admin/ride_zones_controller.rb
- app/models/ride.rb
- app/views/admin/ride_zones/index.html.haml
- app/views/dispatch/_messages.html.haml
- app/views/user_mailer/welcome_email_driver.html.erb
- app/views/user_mailer/welcome_email_not_inlined.html.erb
- app/views/user_mailer/welcome_email_voter.html.erb
- Adds an 'export rides' link to the ride zone admin page, which downloads a CSV of all scheduled rides, to be printed for emergency use in case of loss of power or Internet.
- Couple small copyedits.
Closes #999
> Export scheduled rides, some copyedits

- app/controllers/admin/conversations_controller.rb
- app/controllers/dispatch_controller.rb
- app/models/ride.rb
- app/views/admin/rides/index.html.haml
- app/views/dispatch/_nav.html.haml
- app/views/dispatch/rides.html.haml
- app/views/rides/_form.html.haml
- app/views/rides/_table.html.haml
- app/views/rides/new.html.haml
- config/routes.rb
- spec/controllers/admin/conversation_controller_spec.rb
- spec/factories/conversation_factory.rb
- Adds a 'rides' page to the dispatch app to see upcoming scheduled rides
- Removes contact flyer link
- Set scheduled ride date to election day
Closes #1020, #1018, #1012, #997
> Add scheduled rides page to dispatcher app

- app/views/dispatch/_form.html.haml
> Fix to misspelling from 'XTRA' to 'EXTRA'

- app/assets/javascripts/dispatch.js.erb
- app/assets/stylesheets/dispatch.css.scss
- app/javascript/driving/components/PendingRideDetail.js
Added a little "SR" box in the dispatcher view for rides with special requests. Also fixed a spacing issue in the driver view.
> #1017 make special requests more visible

- app/mailers/application_mailer.rb
- app/mailers/user_mailer.rb
- app/views/user_mailer/welcome_email_driver.html.erb
- config/locales/en.yml
> Update Election Day date and make the email sender have a display name

- app/views/home/_signed_out.html.haml
- app/views/home/about.html.haml
Replacing the fuzzy Squarespace logo with a crisp, shiny SVG
> updating Ragtag logo

- app/controllers/admin/ride_uploads_controller.rb
- app/models/ride_upload.rb
- app/models/user.rb
- app/views/admin/ride_uploads/index.html.haml
Removes methods specific to disk storage, limits CSV upload to 1,000 rows, a few other tweaks
> Fix s3 upload

- app/views/admin/drivers/index.html.haml
- app/views/admin/rides/index.html.haml
- app/views/admin/users/index.html.haml
- app/views/admin/users/voters.html.haml
- app/views/application/_admin_search.html.haml
Small one cleaning admin search views
> DRY admin search

- Gemfile
This PR is a trail change - comment only - to test circleCI pipeline.
> Devise Upgrade to 4.5.0

- config/database.yml
- config/environments/staging.rb
- config/storage.yml
Add DB and config info for a proper staging env.
> add staging environment

- app/views/home/about.html.haml
Per https://github.com/john/drive.vote/issues/1027#issuecomment-431509199.
Addresses #1027
> Change the place we ask people to reach out to for using the app. 

- app/assets/stylesheets/drive.vote.css.scss
- app/views/home/_signed_out.html.haml
Closes #1027 
I haven't been able to get a build running locally so I haven't actually looked at this rendered. @jillh510 can you check the copy for clarity, etc?
> updated homepage with info about 2018 ride zones

- app/views/driving/index.html.haml
- app/views/layouts/application.html.haml
- public/404.html
- public/422.html
- public/500.html
Replace old Zendesk widgets with the new one
> Limit Zendesk widget to DtV articles only

- app/controllers/admin/users_controller.rb
Fixes #1082 -- it looks like the arguments here were just transposed.
> Fix role lists on user page

- app/models/user.rb
- spec/controllers/rides_controller_spec.rb
- spec/fixtures/vcr_cassettes/gmaps.yml
- spec/models/user_spec.rb
Closes #1100, there's an explanation of what it does on that ticket
> remove permissible zip and state

- app/views/dispatch/drivers.html.haml
> fix bad onclick on link_to

- app/assets/javascripts/location_autocomplete.js
- app/controllers/dispatch_controller.rb
- app/views/layouts/mailer.html.erb
- app/views/rides/_form.html.haml
- app/views/user_mailer/welcome_email_not_inlined.html.erb
> Don't prepopulate from city/state
