app/assets/javascripts/application.js
app/assets/javascripts/channels/ride_zone.js
app/channels/application_cable/connection.rb
app/channels/ride_zone_channel.rb
app/controllers/api/v1/twilio_controller.rb
app/controllers/dispatch_controller.rb
app/models/conversation.rb
app/models/message.rb
app/models/ride.rb
app/models/ride_zone.rb
app/models/user.rb
app/views/dispatch/index.html.haml
app/views/layouts/application.html.haml
config/environments/development.rb
config/environments/production.rb
config/routes.rb
doc/drive_the_vote_dispatch_api.md
spec/controllers/api/v1/conversations_controller_spec.rb
spec/controllers/driving_controller_spec.rb
spec/models/conversation_spec.rb
spec/models/message_spec.rb
spec/models/ride_spec.rb
spec/models/user_spec.rb

Two main pieces:
- The javascript and ride_zone_channel.rb and configurations to enable inbound cable connections
- Key objects conversation, ride, message, driver (user) will broadcast events to their ride zone channel on creation and update
@john @messick sorry it's so big, I have a tendency to want to get an entire first pass in vs. adding nibbles at a time. push back if you'd like smaller chunks.
@messick I used the expect syntax on my new tests :-)

First version of the cable-based event API for dispatch

---

public/map/icon-driver.svg
public/map/icon-poll.svg
public/map/icon-voter.svg
public/map/index.html

Introduces a simple web map wrapper for Google Maps or OpenStreetMap-based Leaflet. Features three kinds of map markers, for voters, drivers, and poll locations. Code for this is not yet packaged into a reusable Javascript library.
Remaining work includes:
Sample usage:
```Javascript
new Map(document.getElementById('map'),
function(map) {
map.addMarker(37.770444, -122.434960, map.icons.voter, 'Hello World!', 'http://example.com');
map.addMarker(37.769079, -122.433674, map.icons.poll,  'Hello World!');
map.addMarker(37.771612, -122.426836, map.icons.driver);
},
{lat: 37.77073, lon: -122.43020, zoom: 16});
```

Add map wrapper

---

app/controllers/driving_controller.rb

We should technically explore some mechanism for CSRF protection with the driver app, but this will get us going.

remove CSRF protection for driving API (for now)

---

.circleci/config.yml

Tests started failing due to not being able to find bundler, was hard to debug because our CircleCI config file had been recently auto-generated when we switched from 1.0 to 2.0. Since we're now dockerized I uploaded our image to Docker Hub, and used it as the basis for running CircleCI, rather than one of their generic images.
Config is now easier to read, better mirrors our dev environment, and will better mirror prod as well, if we start deploying via Docker, which would be a Good Idea.

Use our own image for circleci

---

app/controllers/admin/rides_controller.rb
spec/controllers/admin/rides_controller_spec.rb

As prep for #899, this fills out the specs for `POST /admin/rides`. It also changes the redirect response code to [303](https://httpstatuses.com/303), which,
> is primarily used to allow the output of a POST action to redirect the user agent to a selected resource, since doing so provides the information corresponding to the POST response in a form that can be separately identified, bookmarked, and cached, independent of the original request.

✅ add more specs for POST /admin/rides

---

.circleci/config.yml
Dockerfile
Gemfile
Gemfile.lock

*UPDATE: After looking carefully, I'm almost certain we're not using this gem, so updated the PR to remove it entirely. Specs pass.
__
The city-state gem we're using relies on rubyzip 1.1, which has a security vulnerability. The gem isn't being maintained, so I forked it and upgraded rubyzip to the most recent version, 1.2.2.
Because the Gemfile now refers to a git repo rather than just rubygems, it also necessitated updating the Dockerfile to include git, so that gems can be built correctly when creating a new container image.
Note that once this is merged everyone will have to update their local Docker images, since the Dockerfile changed.

Remove city-state gem

---

config/environments/development.rb

This revision addresses an issue in which the development server, when run via `docker-compose up` at least (but probably in other invocations), had no logged output.
Test Plan: Re-ran server and saw general log output from request handling (HTTP level logging, timing, etc), as well as log statements emitted from within a controller. 
Sample output from a now-logged request:
```
web_1    | 22:41:19 web.1     | Started GET "/admin/ride_zones/berkeley" for 172.18.0.1 at 2018-09-07 22:41:19 +0000
web_1    | 22:41:19 web.1     | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
web_1    | 22:41:19 web.1     |    (0.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
web_1    | 22:41:19 …
```

development.rb: Add logging to STDOUT

---

app/assets/javascripts/dispatch.js.erb
app/assets/stylesheets/drive.vote.css.scss
app/controllers/admin/admin_application_controller.rb
app/controllers/admin/conversations_controller.rb
app/controllers/admin/ride_zones_controller.rb
app/controllers/application_controller.rb
app/models/conversation.rb
app/views/admin/ride_zones/edit.html.haml
app/views/admin/ride_zones/index.html.haml
app/views/application/_footer.html.haml
app/views/application/_nav.html.haml
app/views/dispatch/_messages.html.haml
config/environments/development.rb
db/seeds.rb
spec/requests/admin/conversations_spec.rb

Bit of a mishmash, main change is that this allows dispatchers to block phone numbers, previously had been only ride zone admins who could do it. So it reuses the existing blocking code, and just adds a 'Block' button to the RZ modal, and lifts the admin restriction on the controller for blocking.
Also some ad hoc fixes to the ride zone admin pages, previously they were showing all drivers across all ride zones as promotable, it's now scoped just to the ride zone you're looking at.
A few style tweaks to the footer too.
Closes #975

dispatchers can block, admin fixes

---

app/javascript/driving/containers/DriverStatusContainer.js
app/javascript/driving/containers/RideContainer.js
docker-compose.yml

Implements #890 
* Sends a GET request to the `/status` endpoint every 60 seconds
`DriverStatusContainer` is mounted as soon as a driver allows location sharing. Previously this would only check the status just once per session.
@John is this safe to hardcode, or would you like utilize another server-supplied interval, e.g. `waiting_rides_interval`/`update_location_interval`?

Call status endpoint on a set interval

---

Dockerfile
config/database.yml

This PR updates the Heroku production environment to RDS, and standardized images across dev, staging, and prod:
- database.yml is updated to use RDS endpoints for the DB.
- The Dockerfile is updated to use the same base image as is being used in staging and production. Previously staging had been using the heroku-16 base image, production cedar-14, and the local Dockerfile was based on Alpine. Now staging and production have been updated to heroku-18 via the Heroku console, and the local Dockerfile updated to use heroku-18-build, for a consistency across environments.
Closes #968

heroku docker base, RDS in prod

---

app/javascript/driving/components/ActiveRide.js
app/views/application/_footer.html.haml
config/environments/development.rb

- 'Tweet this' button was removed, so Twitter call was pointless and failed
- Copyedits to driver app to clarify the difference between cancelling and archiving
- App should be run on localhost now, not an alias, so update ws:// origin to reflect that

Update cancel copy, fix ws origin, remove twitter

---

app/views/dispatch/_map_key.html.haml
app/views/dispatch/map.html.haml
app/views/dispatch/show.html.haml

Fixes #985 
Adds the map key & UI controls to the large map template so that dispatch_map JS event listeners won't error out on non-existing DOM elements.

Render key and controls for large map, move to a partial

---

app/mailers/user_mailer.rb
app/models/user.rb
app/views/user_mailer/notify_driver_approved.html.erb
spec/mailers/previews/user_mailer_preview.rb
spec/models/user_spec.rb

First (er, second 😕) stab at #715, notifying driver they've been approved/assigned. Draft of email view (also visible in the [previewer](http://localhost:3000/rails/mailers/user_mailer/notify_driver_approved) if you're running locally) is below.

send email when driver is approved (fixes #715)

---

app/controllers/admin/drivers_controller.rb
app/views/dispatch/drivers.html.haml
config/routes.rb
spec/controllers/admin/drivers_controller_spec.rb

Fixes #880. Also replaced emoji characters with HTML entities.
I went with play and pause emoji for the controls (e.g., ▶️ see screenshot), plus tooltips, thinking these will tend to be less-used controls anyway. Just let me know feedback on that; if text or anything else is preferred, that's no sweat, of course).
I also punted on handling this scenario if the driver is mid-ride - disallowing it (with an explanatory JS alert message) until the ride is removed. Happy to dig in further on that or add it in a future feature, whichever is preferred.

add ability for ride-zone admins to set drivers on or off duty

---

app/controllers/admin/ride_uploads_controller.rb
app/models/conversation.rb
app/models/potential_ride.rb
app/models/ride.rb
app/models/user.rb
app/views/admin/ride_uploads/show.html.haml
spec/controllers/admin/ride_uploads_controller_spec.rb
spec/models/ride_spec.rb
spec/requests/admin/conversations_spec.rb

Changes:
- Fewer status changes. They're doing using Rails enum, so a DB call is triggered each time.
- Turn off SMS when bulk uploading rides. We may want to check with ride zone admins about preferred behavior.
- Comments on moving conversion of PotentialRides to Rides to an asynchronous job. That's how it should be done--any upload of more than 200 rides is likely to time out--but I wanted to improve the logic/DB interaction in a discrete step before doing that.

fewer db calls, no sms option on ride creation

---

Gemfile
app/views/application/_staging_banner.html.haml
app/views/layouts/application.html.haml
config/initializers/devise.rb
spec/requests/top_level_spec.rb

This fixes issue #1032 
If the Rails.env is 'production', the app displays as normal.
If the Rails.env is anything other than 'production', it displays a simple one-line white-on-red banner at the top of the page, with text similar to "You are viewing the STAGING environment". 
__NOTE__: this solution makes two key assumptions:
1) In production, Rails.env == 'production'
2) In staging, Rails.env !== 'production'

Add banner to warn about non-prod environments - fixes #1032

---

app/controllers/api/v1/rides_controller.rb
spec/requests/api/v1/rides_spec.rb

- `render :nothing` was removed in Rails 5.2, so switch to `render plain:`
- Require X-Token header rather than leaving it wide open
- Added specs

Fix and add spec for confirm_scheduled

---

.editorconfig
README.md
app/models/conversation.rb
app/models/ride.rb
app/services/conversation_bot.rb
app/views/dispatch/_messages.html.haml
app/views/dispatch/_modal.html.haml
config/locales/en.yml
config/locales/es.yml
spec/models/ride_spec.rb

When a scheduled ride is moved into 'waiting_assignment' status by the cron/scheduled lambda it needs to send the user a notification, which this PR adds. It also fixes an issue with the messages in the conversation modal

Send confirmation for scheduled rides

---

Gemfile
Gemfile.lock

Only change to the gem was to patch an XSS issue, safe upgrade. We were alerted by Github.

Upgrade loofah gem for CVE-2018-16468

---

app/models/ride.rb
app/models/user.rb
app/views/dispatch/drivers.html.haml
spec/models/ride_spec.rb
spec/models/user_spec.rb

Ride.confirm_scheduled_rides was sending notifications, but not changing status. Also updated dispatch /drivers page to make it easier to see when a driver is inactive, and may have just forgotten to check out.

fix status change bug, tweak drivers page

---

app/models/ride.rb
app/views/user_mailer/notify_scheduled_ride.html.erb
spec/models/ride_spec.rb

Two very small changes:
- Remove the validation on Ride state fields that required it to be two characters, to allow the handling of full state names, since in some cases the Google Places API, which we're using for the city/state autocomplete on the ride scheduling form, will return the state name instead of abbreviation. See screenshot below.
- Add standard DtV time zone handling to the email notification that a scheduled ride is coming soon, so it doesn't look like it's coming in 8 hours.

Fix email time zone issue, relax state validation
